"""Parse a product specification file and extract structured info for planning.

The product spec file (e.g. PRODUCT.md) is created by the user — typically by
brainstorming with AI tools — and contains the product vision, features,
requirements, user stories, and technical decisions.  It is separate from
CLAUDE.md (which holds agent/task management rules generated by ``orai init``).
"""

from __future__ import annotations

import re
from pathlib import Path


def parse_product_spec(path: Path) -> dict:
    """Read a product spec file and extract structured information.

    Returns a dict with keys:
        raw_content: full file text
        title: product/project title from the ``# heading``
        sections: dict mapping section title -> content
        features: list of features / user stories
        tech_decisions: list of technical decisions or constraints
        requirements: list of requirements
        pages_routes: list of pages or routes
        data_models: list of data model descriptions
        integrations: list of third-party integrations
        extra_sections: leftover sections not captured above
    """
    content = path.read_text(encoding="utf-8", errors="replace")
    result: dict = {
        "raw_content": content,
        "title": "",
        "sections": {},
        "features": [],
        "tech_decisions": [],
        "requirements": [],
        "pages_routes": [],
        "data_models": [],
        "integrations": [],
        "extra_sections": "",
    }

    # --- Parse title ---
    title_match = re.match(r"^#\s+(.+)", content)
    if title_match:
        result["title"] = title_match.group(1).strip()

    # --- Split into sections by ## headings ---
    sections: dict[str, str] = {}
    current_heading = ""
    current_lines: list[str] = []
    # Also capture text before the first ## (intro paragraph)
    intro_lines: list[str] = []
    seen_heading = False

    for line in content.splitlines():
        heading_match = re.match(r"^##\s+(.+)", line)
        if heading_match:
            if current_heading:
                sections[current_heading] = "\n".join(current_lines).strip()
            current_heading = heading_match.group(1).strip()
            current_lines = []
            seen_heading = True
        elif not seen_heading:
            # Text before first ## heading (skip the # title line)
            if not re.match(r"^#\s+", line):
                intro_lines.append(line)
        else:
            current_lines.append(line)

    if current_heading:
        sections[current_heading] = "\n".join(current_lines).strip()

    result["sections"] = sections

    # If there's an intro paragraph, append to title as description
    intro = "\n".join(intro_lines).strip()
    if intro:
        result["title"] = result["title"] + ("\n" + intro if result["title"] else intro)

    # --- Extract known section types ---
    _match_section(result, "features", sections, [
        "Features", "Key Features", "Core Features", "Feature List",
        "User Stories", "Capabilities", "Functionality",
    ])
    _match_section(result, "tech_decisions", sections, [
        "Tech Stack", "Technical Decisions", "Technology",
        "Architecture", "Architecture Decisions", "Technical Requirements",
        "Stack", "Tech",
    ])
    _match_section(result, "requirements", sections, [
        "Requirements", "Functional Requirements", "Non-Functional Requirements",
        "Constraints", "Specifications", "Specs", "Goals",
    ])
    _match_section(result, "pages_routes", sections, [
        "Pages", "Routes", "Screens", "Views", "Navigation",
        "Page Structure", "URL Structure", "Sitemap",
    ])
    _match_section(result, "data_models", sections, [
        "Data Models", "Models", "Database", "Schema", "Entities",
        "Data Structure", "Database Schema", "DB Schema",
    ])
    _match_section(result, "integrations", sections, [
        "Integrations", "Third-Party", "External Services",
        "APIs", "External APIs", "Services",
    ])

    # --- Collect remaining sections ---
    captured_keys: set[str] = set()
    for field in ("features", "tech_decisions", "requirements",
                  "pages_routes", "data_models", "integrations"):
        captured_keys.update(result.get(f"_matched_{field}", []))

    extra_parts = []
    for key, val in sections.items():
        if key not in captured_keys and val.strip():
            extra_parts.append(f"## {key}\n{val}")
    if extra_parts:
        result["extra_sections"] = "\n\n".join(extra_parts)

    # Clean up internal keys
    for field in ("features", "tech_decisions", "requirements",
                  "pages_routes", "data_models", "integrations"):
        result.pop(f"_matched_{field}", None)

    return result


def _match_section(
    result: dict,
    field: str,
    sections: dict[str, str],
    candidates: list[str],
) -> None:
    """Find matching section(s) and extract list items into result[field]."""
    matched_keys: list[str] = []
    items: list[str] = []

    for candidate in candidates:
        candidate_lower = candidate.lower()
        for key, val in sections.items():
            if key.lower() == candidate_lower or candidate_lower in key.lower():
                if key not in matched_keys:
                    matched_keys.append(key)
                    items.extend(_extract_list_items(val))

    result[field] = items
    result[f"_matched_{field}"] = matched_keys


def _extract_list_items(text: str) -> list[str]:
    """Extract bullet/dash/numbered list items from text."""
    items = []
    for line in text.splitlines():
        line = line.strip()
        # Bullet or dash list
        match = re.match(r"^[-*]\s+(.+)", line)
        if match:
            items.append(match.group(1).strip())
            continue
        # Numbered list (1. item, 1) item)
        match = re.match(r"^\d+[.)]\s+(.+)", line)
        if match:
            items.append(match.group(1).strip())
            continue
        # Non-empty, non-heading, non-code-fence lines (paragraph text)
        if line and not line.startswith("#") and not line.startswith("```"):
            items.append(line)
    return [item for item in items if item]


def build_spec_context(parsed: dict) -> str:
    """Build a structured context string from a parsed product spec for the planner."""
    parts = []

    if parsed["title"]:
        parts.append(f"**Product:** {parsed['title']}")

    if parsed["features"]:
        feats = "\n".join(f"  - {f}" for f in parsed["features"])
        parts.append(f"**Features:**\n{feats}")

    if parsed["tech_decisions"]:
        tech = "\n".join(f"  - {t}" for t in parsed["tech_decisions"])
        parts.append(f"**Technical Decisions:**\n{tech}")

    if parsed["requirements"]:
        reqs = "\n".join(f"  - {r}" for r in parsed["requirements"])
        parts.append(f"**Requirements:**\n{reqs}")

    if parsed["pages_routes"]:
        pages = "\n".join(f"  - {p}" for p in parsed["pages_routes"])
        parts.append(f"**Pages / Routes:**\n{pages}")

    if parsed["data_models"]:
        models = "\n".join(f"  - {m}" for m in parsed["data_models"])
        parts.append(f"**Data Models:**\n{models}")

    if parsed["integrations"]:
        integ = "\n".join(f"  - {i}" for i in parsed["integrations"])
        parts.append(f"**Integrations:**\n{integ}")

    if parsed["extra_sections"]:
        parts.append(f"**Additional Product Context:**\n{parsed['extra_sections']}")

    # Always include raw content — structured extraction may miss nuance
    parts.append(
        "**Full Product Specification (raw):**\n"
        f"```markdown\n{parsed['raw_content']}\n```"
    )

    return "\n\n".join(parts)
